schema_version: 1

context:
  name: pep517
  version: "0.13.0"
  python_min: "3.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ae69927c5c172be1add9203726d4b84cf3ebad1edcd5f71fcdc746e66e829f59

build:
  noarch: python
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core >=2,<3
  run:
    - python >=${{ python_min }}
    - tomli

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - pep517
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://pypi.org/project/pep517/
  license: MIT
  license_file: LICENSE
  summary: Wrappers to build Python packages using PEP 517 hooks

extra:
  recipe-maintainers:
    - ocefpaf
